language: generic
sudo: required
services:
  - docker
before_install:
  - 'docker build -t vinnieschoonen/react-test -f ./client/Dockerfile.dev ./client'
script:
  - 'docker run vinnieschoonen/react-test npm test -- --coverage'
after_success:
  - 'docker build -t vinnieschoonen/multi-client ./client'
  - 'docker build -t vinnieschoonen/multi-nginx ./nginx'
  - 'docker build -t vinnieschoonen/multi-server ./server'
  - 'docker build -t vinnieschoonen/multi-worker ./worker'
  - 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin'
  - 'docker push multi-client'
  - 'docker push multi-nginx'
  - 'docker push multi-server'
  - 'docker push multi-worker'
